//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glyssen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glyssen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _112_Plus_Green_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("112_Plus_Green_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John
        ///250 Israelite leaders	250	Male	Adult		
        ///a Jew	1	Male	Adult		
        ///Aaron	1	Male	Adult		
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah
        ///Abigail	1	Female	Adult		
        ///Abijah, king of Judah	1	Male	Adult		
        ///Abimelech, king of Gerar	1	Male	Adult		
        ///Abimelech, king of the Philistines (in Gerar)	1	Male	Adult		
        ///Abimelech, son of Gideon (Jerubbaal)	1	Male	Adult		
        ///Abiram	1	Male	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterDetail {
            get {
                return ResourceManager.GetString("CharacterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CharacterGroups {
            get {
                object obj = ResourceManager.GetObject("CharacterGroups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] CharacterGroups_FCBH {
            get {
                object obj = ResourceManager.GetObject("CharacterGroups_FCBH", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	78
        ///#	C	V	Character ID	Delivery	Alias	Quote Type	Default Character	Parallel Passage
        ///# DEU Almost the whole book is by Moses -- In some Bibles, first level quotes are actually 2nd level -- see DEU 1.5								
        ///# PSA will be handled as complete units, each psalm will be spoken by one voice								
        ///# SNG we will need to review again								
        ///# ISA more review necessary on who is speaking: God or the Isaiah								
        ///# JER possibly no markup of this book... will need to review								
        ///# E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterVerseData {
            get {
                return ResourceManager.GetString("CharacterVerseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DecreaseSize {
            get {
                object obj = ResourceManager.GetObject("DecreaseSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;English&quot;
        ///# Version=1.9
        ///#
        ///# modifications by Reinier de Blois 13/March/2012
        ///# modified mappings Psalms by adding verse #0 to the mappings
        ///# many of the subscripts that are part of verses 1,2 in the original text end up as verse #0 in English translations
        ///
        ///# modifications by Studge 26/June/2009
        ///# book definitions are for all books printed in any English of Spanish Bible
        ///# this includes books for Protestant, Catholic and Protestant-Catholic-EasternOrthodox Interconfessional editions        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishVersification {
            get {
                return ResourceManager.GetString("EnglishVersification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon glyssenIcon {
            get {
                object obj = ResourceManager.GetObject("glyssenIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_check {
            get {
                object obj = ResourceManager.GetObject("green_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid_icon {
            get {
                object obj = ResourceManager.GetObject("grid_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpSmall {
            get {
                object obj = ResourceManager.GetObject("helpSmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap html_view {
            get {
                object obj = ResourceManager.GetObject("html_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IncreaseSize {
            get {
                object obj = ResourceManager.GetObject("IncreaseSize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QuoteSystems&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, double&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, US/Canada&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Tırnak işareti (with 2014 Quotation dash)&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;Turkish/Vietnamese&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///    &lt;QuotationDashMarker&gt;—&lt;/QuotationDashMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSyste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteSystemData {
            get {
                return ResourceManager.GetString("QuoteSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Marako Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Marako&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mar&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok ma Jon Labatija otit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleMRK {
            get {
                return ResourceManager.GetString("SampleMRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_glyph {
            get {
                object obj = ResourceManager.GetObject("search_glyph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplitBlock {
            get {
                object obj = ResourceManager.GetObject("SplitBlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap undo {
            get {
                object obj = ResourceManager.GetObject("undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_ok_icon {
            get {
                object obj = ResourceManager.GetObject("yellow_ok_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
