//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glyssen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserInterfaceLanguage {
            get {
                return ((string)(this["UserInterfaceLanguage"]));
            }
            set {
                this["UserInterfaceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentProject {
            get {
                return ((string)(this["CurrentProject"]));
            }
            set {
                this["CurrentProject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultBundleDirectory {
            get {
                return ((string)(this["DefaultBundleDirectory"]));
            }
            set {
                this["DefaultBundleDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultExportDirectory {
            get {
                return ((string)(this["DefaultExportDirectory"]));
            }
            set {
                this["DefaultExportDirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public int ParserVersion {
            get {
                return ((int)(this["ParserVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DefaultFontSize {
            get {
                return ((int)(this["DefaultFontSize"]));
            }
            set {
                this["DefaultFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSfmDirectory {
            get {
                return ((string)(this["DefaultSfmDirectory"]));
            }
            set {
                this["DefaultSfmDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AssignCharactersShowGridView {
            get {
                return ((bool)(this["AssignCharactersShowGridView"]));
            }
            set {
                this["AssignCharactersShowGridView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings AssignCharacterDialogFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["AssignCharacterDialogFormSettings"]));
            }
            set {
                this["AssignCharacterDialogFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.GridSettings AssignCharactersBlockContextGrid {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.GridSettings)(this["AssignCharactersBlockContextGrid"]));
            }
            set {
                this["AssignCharactersBlockContextGrid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuoteMarksDialogShowGridView {
            get {
                return ((bool)(this["QuoteMarksDialogShowGridView"]));
            }
            set {
                this["QuoteMarksDialogShowGridView"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DataFormatVersion {
            get {
                return ((int)(this["DataFormatVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings OpenProjectDlgFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["OpenProjectDlgFormSettings"]));
            }
            set {
                this["OpenProjectDlgFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.GridSettings OpenProjectDlgGridSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.GridSettings)(this["OpenProjectDlgGridSettings"]));
            }
            set {
                this["OpenProjectDlgGridSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedUpgrade {
            get {
                return ((bool)(this["NeedUpgrade"]));
            }
            set {
                this["NeedUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AssignCharactersSliderLocation {
            get {
                return ((int)(this["AssignCharactersSliderLocation"]));
            }
            set {
                this["AssignCharactersSliderLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SampleVersion {
            get {
                return ((int)(this["SampleVersion"]));
            }
            set {
                this["SampleVersion"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("95")]
        public double TargetPercentageOfQuotesFound {
            get {
                return ((double)(this["TargetPercentageOfQuotesFound"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double MaxAcceptablePercentageOfUnknownQuotes {
            get {
                return ((double)(this["MaxAcceptablePercentageOfUnknownQuotes"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings VoiceActorInformationDlgFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["VoiceActorInformationDlgFormSettings"]));
            }
            set {
                this["VoiceActorInformationDlgFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings VoiceActorAssignmentDlgFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["VoiceActorAssignmentDlgFormSettings"]));
            }
            set {
                this["VoiceActorAssignmentDlgFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.GridSettings CharacterGroupGridGridSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.GridSettings)(this["CharacterGroupGridGridSettings"]));
            }
            set {
                this["CharacterGroupGridGridSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings SplitBlockDlgFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["SplitBlockDlgFormSettings"]));
            }
            set {
                this["SplitBlockDlgFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings QuotationMarksDlgFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["QuotationMarksDlgFormSettings"]));
            }
            set {
                this["QuotationMarksDlgFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int QuotationMarksDlgSplitterDistance {
            get {
                return ((int)(this["QuotationMarksDlgSplitterDistance"]));
            }
            set {
                this["QuotationMarksDlgSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings ProjectSettingsDlgFormSettings {
            get {
                return ((global::SIL.Windows.Forms.PortableSettingsProvider.FormSettings)(this["ProjectSettingsDlgFormSettings"]));
            }
            set {
                this["ProjectSettingsDlgFormSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AssignCharactersMatchReferenceText {
            get {
                return ((bool)(this["AssignCharactersMatchReferenceText"]));
            }
            set {
                this["AssignCharactersMatchReferenceText"] = value;
            }
        }
    }
}
