//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glyssen.ReferenceTextUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glyssen.ReferenceTextUtility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata&gt;
        ///  &lt;language&gt;
        ///    &lt;fontFamily&gt;Charis SIL&lt;/fontFamily&gt;
        ///    &lt;fontSizeInPoints&gt;14&lt;/fontSizeInPoints&gt;
        ///  &lt;/language&gt;
        ///  &lt;copyright&gt;
        ///    &lt;statement contentType=&quot;xhtml&quot;&gt;
        ///    &lt;/statement&gt;
        ///  &lt;/copyright&gt;
        ///  &lt;promotion&gt;
        ///    &lt;promoVersionInfo contentType=&quot;xhtml&quot; /&gt;
        ///  &lt;/promotion&gt;
        /// &lt;projectStatus&gt;
        ///    &lt;quoteSystemStatus&gt;UserSet&lt;/quoteSystemStatus&gt;
        ///    &lt;quoteSystemDate&gt;2016-03-08T12:27:38.1500615-07:00&lt;/quoteSystemDate&gt;
        ///    &lt;bookSelectionStatus&gt;Reviewed&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string refTextMetadata {
            get {
                return ResourceManager.GetString("refTextMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RefTextUtility {
            get {
                object obj = ResourceManager.GetObject("RefTextUtility", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
