version: '{build}'
branches:
  only:
  - master
  - add-symbols-for-nuget-packages
image: Visual Studio 2019
platform: Any CPU
init:
- cmd: set GITVERSION_BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%
environment:
  ExtraExcludeCategories: SkipOnTeamCity
  Platform: Any CPU
nuget:
  disable_publish_on_pr: true
  disable_publish_octopus: true
build:
  project: build/Glyssen.proj
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
test:
  assemblies:
    except:
    - output\**\SIL.*
  categories:
    except:
    - SkipOnTeamCity
artifacts:
- path: output/*nupkg
  name: nuget
deploy:
- provider: Environment
  name: sil-lsdev nuget
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: false
