//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyssenEngineTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyssenEngineTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Original&quot; 
        ///# Version=1.200
        ///# (not a very good name but I have not heard a better suggestion)
        ///#
        ///# modifications by Studge 26/June/2009
        ///# TomB removed deuterocanical books not needed by Glyssen&apos;s tests
        ///#
        ///# BHS versification for OT, UBS GNT versification for NT
        ///# following the Masoretic order
        ///# OT translations using Masorteic verse structures should map onto this text
        ///# NT versifications maps onto Nestle-Aland
        ///#
        ///# List of books, chapters, verses
        ///# One line per book.
        ///# One entry  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OriginalVersification {
            get {
                return ResourceManager.GetString("OriginalVersification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Russian Orthodox&quot;
        ///# Version=1.3
        ///#
        ///# This is the versification used by the Orthodox (or &quot;non-canonical&quot;) edition of the Russian Synodal Bible
        ///# Initial version provided by Peter_Kirk@sil.org
        ///# Corrected 27/May/2003 by matjaz.crnivec@drustvo-svds.si:
        ///#   Number of vss: 2CH 37; PSA 114; ISA 3; REV 12; 2ES (whole book added),
        ///#   Mappings: LEV 14; 1KI 22; 1CH 12; 2CH 37; NEH 7; PSA 114; ISA 3; 2CO 11; REV 13; 2ES 7; 10
        ///#
        ///# modifications by Studge 26/June/2009
        ///# amended by HAB April 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RussianOrthodoxVersification {
            get {
                return ResourceManager.GetString("RussianOrthodoxVersification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;1CO&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;1 JO KORINT&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Mukwoŋo Ma Paulo Ocoyo Pa Jo Korint&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;1 Jo Korint&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;1 Kor&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MUKWOŊO MA PAULO OCOYO pa&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO KORINT&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test1CO {
            get {
                return ResourceManager.GetString("Test1CO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;1JN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;1 JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Mukwoŋo Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;1 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;1 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MUKWOŊO ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok me kwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test1JN {
            get {
                return ResourceManager.GetString("Test1JN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;2JN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;2 JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Me Aryo Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;2 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;2 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA ME ARYO ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test2JN {
            get {
                return ResourceManager.GetString("Test2JN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;3JN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;3 JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Me Adek Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;3 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;3 JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA ME ADEK ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test3JN {
            get {
                return ResourceManager.GetString("Test3JN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;ACT&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;TIC PA LUKWENA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Tic Pa Lukwena&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Tic Pa Lukwena&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Tic&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;TIC PA LUKWENA&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lubaŋa ociko pi bino pa Cwiny Maleŋ&lt;/para&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestACT {
            get {
                return ResourceManager.GetString("TestACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestCharacterGroups {
            get {
                object obj = ResourceManager.GetObject("TestCharacterGroups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;{0}&quot; style=&quot;id&quot;&gt;A&lt;/book&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; style=&quot;v&quot; /&gt;A.&lt;/para&gt;
        ///&lt;/usx&gt;.
        /// </summary>
        internal static string TestEmptyBook {
            get {
                return ResourceManager.GetString("TestEmptyBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;EPH&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JO EPECO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Paulo Ocoyo Bot Jo Epeco&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jo Epeco&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Ep&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA PAULO OCOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO EPECO&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt;
        ///  &lt;para s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEPH {
            get {
                return ResourceManager.GetString("TestEPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;GAL&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JO GALATIA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Paulo Ocoyo Bot Jo Galatia&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jo Galatia&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Gal&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA PAULO OCOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO GALATIA&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestGAL {
            get {
                return ResourceManager.GetString("TestGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;HEB&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JO IBRU&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Gicoyo Bot Jo Ibru&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jo Ibru&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Ibru&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA GICOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO IBRU&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lubaŋa oloko kwedwa i Wode&lt;/para&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestHEB {
            get {
                return ResourceManager.GetString("TestHEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;JHN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Jon&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok odoko dano&lt;/para&gt;
        ///  &lt;para style [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJHN {
            get {
                return ResourceManager.GetString("TestJHN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;JOS&quot; style=&quot;id&quot;&gt;- Kuna, San Blas - Bible -Panama 2014 (DBL -2014)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Josué&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Josué-Garda&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Josué&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Jos&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JOSUÉ-GARDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JOSUÉ&lt;/para&gt;
        ///  &lt;para style=&quot;imt2&quot;&gt;GEBE-SOGLENAID&lt;/para&gt;
        ///  &lt;para style=&quot;imt&quot;&gt;Garda-nug&lt;/para&gt;
        ///  &lt;para style=&quot;ip&quot;&gt;
        ///    &lt;char style=&quot;it&quot;&gt;Josué-Garda.&lt;/char&gt; Josu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJOS {
            get {
                return ResourceManager.GetString("TestJOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;JOS&quot; style=&quot;id&quot;&gt;- Kuna, San Blas - Bible -Panama 2014 (DBL -2014)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Josué&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Josué-Garda&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Josué&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Jos&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JOSUÉ-GARDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JOSUÉ&lt;/para&gt;
        ///  &lt;para style=&quot;imt2&quot;&gt;GEBE-SOGLENAID&lt;/para&gt;
        ///  &lt;para style=&quot;imt&quot;&gt;Garda-nug&lt;/para&gt;
        ///  &lt;para style=&quot;ip&quot;&gt;
        ///    &lt;char style=&quot;it&quot;&gt;Josué-Garda.&lt;/char&gt; Josu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJOS1 {
            get {
                return ResourceManager.GetString("TestJOS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;JUD&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JUDA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Juda Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Juda&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Juda&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JUDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; styl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJUD {
            get {
                return ResourceManager.GetString("TestJUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;LUK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;LUKA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Luka Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Luka&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Luka&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;LUKA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok bot Teopilo&lt;/para&gt;
        ///  &lt;para [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestLUK {
            get {
                return ResourceManager.GetString("TestLUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MAT&quot; style=&quot;id&quot;&gt;- Kuna, San Blas - Bible -Panama 2014 (DBL -2014)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Mateo&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Mateo-Gayaburba-Nued&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Mateo&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mt&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MATEO-GAYABURBA-NUED&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;MATEO&lt;/para&gt;
        ///  &lt;para style=&quot;imt2&quot;&gt;GEBE-SOGLENAID&lt;/para&gt;
        ///  &lt;para style=&quot;imt&quot;&gt;Garda-nug&lt;/para&gt;
        ///  &lt;para style=&quot;ip&quot;&gt;Mateo we-garda narmaksad. Mate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMATcuk {
            get {
                return ResourceManager.GetString("TestMATcuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Marako Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Marako&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mar&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok ma Jon Labatija otit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMRK {
            get {
                return ResourceManager.GetString("TestMRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;NUM&quot; style=&quot;id&quot;&gt;Some Bible from Asia&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;SÁCH DÂN SỐ&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;SÁCH DÂN SỐ&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;SÁCH DÂN SỐ&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;ms&quot;&gt;I. KIỂM TRA DÂN SỐ&lt;/para&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; style=&quot;v&quot; /&gt;Tại sa mạc Xi-nai ngày mồng một hai năm hai kể từ khi cái Ít-ra-en ra khỏi đất Ai-cập, ĐỨC CHÚA phán với ông Mô-sê trong Lều Hội Ngộ rằng [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestNUM {
            get {
                return ResourceManager.GetString("TestNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.5&quot;&gt;
        ///  &lt;book code=&quot;OBA&quot; style=&quot;id&quot;&gt;O&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;O&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;O&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; style=&quot;v&quot; /&gt;Verse 1 text. &lt;verse number=&quot;2-6a&quot; style=&quot;v&quot; /&gt;Verses 2-6a text. &lt;verse number=&quot;6b-11&quot; style=&quot;v&quot; /&gt;Verses 6b-11 text. &lt;verse number=&quot;12-16&quot; style=&quot;v&quot; /&gt;Verses 12-16 text. &lt;verse number=&quot;17&quot; style=&quot;v&quot; /&gt;Verse 17 text. &lt;/para&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestOBAwithInterestingVerseNums {
            get {
                return ResourceManager.GetString("TestOBAwithInterestingVerseNums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;PHM&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;PILEMON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Paulo Ocoyo Bot Pilemon Mot&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Pilemon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Pile&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA PAULO OCOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;PILEMON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;Mot&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPHM {
            get {
                return ResourceManager.GetString("TestPHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;REV&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;NIYABO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Niyabo Bot Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Niyabo&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Yabo&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;NIYABO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;BOT JON&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; style=&quot;v&quot; /&gt;Man aye gin ma Lubaŋa onyuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestREV {
            get {
                return ResourceManager.GetString("TestREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;RUT&quot; style=&quot;id&quot;&gt;- Kuna, San Blas - Bible -Panama 2014 (DBL -2014)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Rut&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Rut-Garda&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Rut&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Rt&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;RUT-GARDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;RUT&lt;/para&gt;
        ///  &lt;para style=&quot;imt2&quot;&gt;GEBE-SOGLENAID&lt;/para&gt;
        ///  &lt;para style=&quot;imt&quot;&gt;Garda-nug&lt;/para&gt;
        ///  &lt;para style=&quot;ip&quot;&gt;
        ///    &lt;char style=&quot;it&quot;&gt;Rut-Garda.&lt;/char&gt; We-gardagine, bun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRUT {
            get {
                return ResourceManager.GetString("TestRUT", resourceCulture);
            }
        }
    }
}
