//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyssenEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyssenEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISA	14	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///ISA	14	27	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	1	2	0	&lt;Sound startVerse=&quot;2&quot; /&gt;
        ///MAT	1	17	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	2	8	0	&lt;Sound startVerse=&quot;8&quot; /&gt;
        ///MAT	4	11	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	4	17	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	4	22	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	6	7	0	&lt;Sound endVerse=&quot;7&quot; /&gt;
        ///MAT	6	15	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	7	2	0	&lt;Sound startVerse=&quot;2&quot; /&gt;
        ///MAT	8	4	0	&lt;Pause time=&quot;1.5&quot; /&gt;
        ///MAT	8	11	0	&lt;Sound endVerse=&quot;11&quot; /&gt;
        ///MAT	8	13	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	8	17	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///MAT	8	22	0	&lt;Pause tim [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BiblicalAuthors&gt;
        ///	&lt;Author name=&quot;Moses&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;GEN&lt;/Book&gt;
        ///			&lt;Book&gt;EXO&lt;/Book&gt;
        ///			&lt;Book&gt;LEV&lt;/Book&gt;
        ///			&lt;Book&gt;NUM&lt;/Book&gt;
        ///			&lt;Book&gt;DEU&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Joshua&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;JOS&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Author of Judges&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;JDG&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Author of Ruth&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;RUT&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Samuel&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;1SA&lt;/Book&gt;
        ///			&lt;Book&gt;2S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BiblicalAuthors {
            get {
                return ResourceManager.GetString("BiblicalAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///select {
        ///    float: right;
        ///    margin-bottom: 6px;
        ///}
        ///
        ///.splittext {
        ///    cursor: col-resize;
        ///}
        ///
        ///.split-line {
        ///    cursor: url(&apos;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAK3RFWHRDcmVhdGlvbiBUaW1lAFR1ZSA0IERlYyAyMDA3IDIyOjA4OjM1IC0wNTAwrRqIvgAAAAd0SU1FB9gDBQQwNlUytbYAAAAJcEhZcwAACvAAAArwAUKsNJgAAAAEZ0FNQQAAsY8L/GEFAAACx0lEQVR42t1WTWsTURQ90zh+1TY1fkaUQhWrCyFB0apbl/0DLl2JuFEEpaC/okZEuhD8D66suBXFlQhuBBdGRGqspKbamOe5mfvic5h5SZ12Cl44Gcgb5px37sd7AQBDHCC+EZuJn8QScopABUiME9uJJtFQI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlockSplitCss {
            get {
                return ResourceManager.GetString("BlockSplitCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Sample&quot;
        ///# Version=2.0
        ///#
        ///# modifications by Reinier de Blois 13/March/2012
        ///# modified mappings Psalms by adding verse #0 to the mappings
        ///# many of the subscripts that are part of verses 1,2 in the original text end up as verse #0 in English translations
        ///
        ///# modifications by Studge 26/June/2009
        ///# book definitions are for all books printed in any English of Spanish Bible
        ///# this includes books for Protestant, Catholic and Protestant-Catholic-EasternOrthodox Interconfessional editions
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishVersification {
            get {
                return ResourceManager.GetString("EnglishVersification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QuoteSystems&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, double&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, US/Canada&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Tırnak işareti (with 2014 Quotation dash)&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;Turkish/Vietnamese&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///    &lt;QuotationDashMarker&gt;—&lt;/QuotationDashMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSyste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteSystemData {
            get {
                return ResourceManager.GetString("QuoteSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;- Sea Island Creole English (Gullah) NT -USA 2005 (DBL 2013)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Mark&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;De Good Nyews Bout Jedus Christ Wa Mark Write&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Mark&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mr&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;De Good Nyews Bout Jedus Christ Wa Mark Write&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s&quot;&gt;John wa Bactize People Mek de Way&lt;/para&gt;
        ///  &lt;para st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleMRK {
            get {
                return ResourceManager.GetString("SampleMRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Silent {
            get {
                return ResourceManager.GetStream("Silent", resourceCulture);
            }
        }
    }
}
