//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyssenEngine {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyssenEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEN	1	30	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	2	25	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	3	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	4	26	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	5	32	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	6	22	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	7	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	8	22	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	9	29	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	10	32	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	11	32	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	12	20	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	13	18	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	14	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	15	19	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	16	16	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	17	27 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;BiblicalAuthors&gt;
        ///	&lt;Author name=&quot;Moses&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;GEN&lt;/Book&gt;
        ///			&lt;Book&gt;EXO&lt;/Book&gt;
        ///			&lt;Book&gt;LEV&lt;/Book&gt;
        ///			&lt;Book&gt;NUM&lt;/Book&gt;
        ///			&lt;Book&gt;DEU&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Joshua&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;JOS&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Author of Judges&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;JDG&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Author of Ruth&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;RUT&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Samuel&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;1SA&lt;/Book&gt;
        ///			&lt;Book&gt;2S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BiblicalAuthors {
            get {
                return ResourceManager.GetString("BiblicalAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment	Reference	FCBH Character
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John	JHN 21:3 &amp; JHN 21:5
        ///250 Israelite leaders	250	Male	Adult			NUM 16:3
        ///a Jew	1	Male	Adult			JHN 3:26
        ///Aaron	1	Male	Adult			EXO 5:1 &lt;-(16 more)-&gt; NUM 16:22
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah	DAN 3:16 &lt;-(1 more)-&gt; DAN 3:18
        ///Abigail	1	Female	Adult			1SA 25:19 &lt;-(8 more)-&gt; 1SA 25:41
        ///Abijah, king of Judah	1	Male	Adult			2CH 13:4 &lt;-( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterDetail {
            get {
                return ResourceManager.GetString("CharacterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QuoteSystems&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, double&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, US/Canada&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Tırnak işareti (with 2014 Quotation dash)&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;Turkish/Vietnamese&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///    &lt;QuotationDashMarker&gt;—&lt;/QuotationDashMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSyste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteSystemData {
            get {
                return ResourceManager.GetString("QuoteSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RelatedCharacterSets&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;Barzillai&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;Barzillai (old)&lt;/CharacterId&gt;
        ///	&lt;/RelatedCharacters&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;David&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;David (old)&lt;/CharacterId&gt;
        ///	&lt;/RelatedCharacters&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;Elisha&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;Elisha (old)&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelatedCharacters {
            get {
                return ResourceManager.GetString("RelatedCharacters", resourceCulture);
            }
        }
    }
}
