[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("ControlDataIntegrityTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("GlyssenTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("GlyssenEngineTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("GlyssenCharactersTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("DevTools")]
