//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Waxuquerque.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Waxuquerque.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GEN	1	30	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	2	25	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	3	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	4	26	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	5	32	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	6	22	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	7	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	8	22	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	9	29	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	10	32	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	11	32	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	12	20	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	13	18	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	14	24	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	15	19	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	16	16	0	&lt;Pause time=&quot;2&quot; /&gt;
        ///GEN	17	27 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Annotations {
            get {
                return ResourceManager.GetString("Annotations", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;BiblicalAuthors&gt;
        ///	&lt;Author name=&quot;Moses&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;GEN&lt;/Book&gt;
        ///			&lt;Book&gt;EXO&lt;/Book&gt;
        ///			&lt;Book&gt;LEV&lt;/Book&gt;
        ///			&lt;Book&gt;NUM&lt;/Book&gt;
        ///			&lt;Book&gt;DEU&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Joshua&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;JOS&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Author of Judges&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;JDG&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Author of Ruth&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;RUT&lt;/Book&gt;
        ///		&lt;/Books&gt;
        ///	&lt;/Author&gt;
        ///	&lt;Author name=&quot;Samuel&quot;&gt;
        ///		&lt;Books&gt;
        ///			&lt;Book&gt;1SA&lt;/Book&gt;
        ///			&lt;Book&gt;2S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BiblicalAuthors {
            get {
                return ResourceManager.GetString("BiblicalAuthors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment	Reference Comment
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John
        ///250 Israelite leaders	250	Male	Adult
        ///a Jew	1	Male	Adult
        ///Aaron	1	Male	Adult			EXO 32:2 &lt;-(6 more)-&gt; NUM 12:12
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah
        ///Abigail	1	Female	Adult			1SA 25:19 &lt;-(8 more)-&gt; 1SA 25:41
        ///Abijah, king of Judah	1	Male	Adult			2CH 13:4 &lt;-(7 more)-&gt; 2CH 13:12
        ///Abimelech, king of Gerar	1	Male	Adult			GEN 20:4 &lt;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterDetail {
            get {
                return ResourceManager.GetString("CharacterDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control File Version	125
        ///#	C	V	Character ID	Delivery	Alias	Quote Type	Default Character	Parallel Passage
        ///# DEU Almost the whole book is by Moses -- In some Bibles, first level quotes are actually 2nd level -- see DEU 1.5
        ///# PSA will be handled as complete units, each psalm will be spoken by one voice
        ///# SNG we will need to review again
        ///# ISA more review necessary on who is speaking: God or the Isaiah
        ///# JER possibly no markup of this book... will need to review
        ///#  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterVerseData {
            get {
                return ResourceManager.GetString("CharacterVerseData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Sample&quot;
        ///# Version=1.9
        ///#
        ///# modifications by Reinier de Blois 13/March/2012
        ///# modified mappings Psalms by adding verse #0 to the mappings
        ///# many of the subscripts that are part of verses 1,2 in the original text end up as verse #0 in English translations
        ///
        ///# modifications by Studge 26/June/2009
        ///# book definitions are for all books printed in any English of Spanish Bible
        ///# this includes books for Protestant, Catholic and Protestant-Catholic-EasternOrthodox Interconfessional editions
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishVersification {
            get {
                return ResourceManager.GetString("EnglishVersification", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;QuoteSystems&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, double&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, US/Canada&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Tırnak işareti (with 2014 Quotation dash)&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;Turkish/Vietnamese&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///    &lt;QuotationDashMarker&gt;—&lt;/QuotationDashMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSyste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteSystemData {
            get {
                return ResourceManager.GetString("QuoteSystemData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;RelatedCharacterSets&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;Barzillai&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;Barzillai (old)&lt;/CharacterId&gt;
        ///	&lt;/RelatedCharacters&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;David&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;David (old)&lt;/CharacterId&gt;
        ///	&lt;/RelatedCharacters&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;Elisha&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;Elisha (old)&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RelatedCharacters {
            get {
                return ResourceManager.GetString("RelatedCharacters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;- Sea Island Creole English (Gullah) NT -USA 2005 (DBL 2013)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Mark&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;De Good Nyews Bout Jedus Christ Wa Mark Write&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Mark&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mr&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;De Good Nyews Bout Jedus Christ Wa Mark Write&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s&quot;&gt;John wa Bactize People Mek de Way&lt;/para&gt;
        ///  &lt;para st [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleMRK {
            get {
                return ResourceManager.GetString("SampleMRK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Silent {
            get {
                return ResourceManager.GetStream("Silent", resourceCulture);
            }
        }
    }
}
