//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _112_Plus_Green_16x16_72 {
            get {
                object obj = ResourceManager.GetObject("112_Plus_Green_16x16_72", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Code (discard)	Multiple Speakers	Gender	Age	Comment
        ///Aaron	1	FALSE	Male		
        ///Abigail	2	FALSE	Female		
        ///Abijah, king of Judah	3	FALSE	Male		
        ///Abimelech, King of Gerar	4	FALSE	Male		
        ///Abimelech, King of Gerar/Phicol		TRUE	Male		
        ///Abimelech, King of the Philistines (in Gerar)		FALSE	Male		
        ///Abimelech, son of Gideon		FALSE	Male		
        ///Abishai, Joab&apos;s brother	5	FALSE	Male		
        ///Abner	6	FALSE	Male		
        ///Abraham	7	FALSE	Male		
        ///Abraham&apos;s chief servant	8	FALSE	Male		
        ///Absalom	10	FALSE	Male		
        ///Absalom&apos;s men	11	TRU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterIdMap {
            get {
                return ResourceManager.GetString("CharacterIdMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	40
        ///#	C	V	Character ID	Delivery	Alias	Dialogue	Default Character	Parallel Passage
        ///GEN	1	3	God		God (the LORD)	FALSE		
        ///GEN	1	5	narrator-GEN			FALSE		
        ///GEN	1	6	God		God (the LORD)	FALSE		
        ///GEN	1	8	narrator-GEN			FALSE		
        ///GEN	1	9	God		God (the LORD)	FALSE		
        ///GEN	1	10	narrator-GEN			FALSE		
        ///GEN	1	11	God		God (the LORD)	FALSE		
        ///GEN	1	14	God		God (the LORD)	FALSE		
        ///GEN	1	20	God		God (the LORD)	FALSE		
        ///GEN	1	22	God		God (the LORD)	FALSE		
        ///GEN	1	24	God		God (the LORD)	FALSE		
        ///GEN	1	26	G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterVerseData {
            get {
                return ResourceManager.GetString("CharacterVerseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap grid_icon {
            get {
                object obj = ResourceManager.GetObject("grid_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap html_view {
            get {
                object obj = ResourceManager.GetObject("html_view", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QuoteSystems&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, double&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, US/Canada&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Tırnak işareti (with 2014 Quotation dash)&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;Turkish/Vietnamese&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///    &lt;QuotationDashMarker&gt;—&lt;/QuotationDashMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///  	&lt;QuoteSyste [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteSystemData {
            get {
                return ResourceManager.GetString("QuoteSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Marako Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Marako&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mar&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok ma Jon Labatija otit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleMRK {
            get {
                return ResourceManager.GetString("SampleMRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_glyph {
            get {
                object obj = ResourceManager.GetObject("search_glyph", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow_ok_icon {
            get {
                object obj = ResourceManager.GetObject("yellow_ok_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
