//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoScript.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoScript.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	6	Generated	Wed, 10 Dec 2014 15:12:22 GMT
        ///GEN	1	3	God		God (the LORD)
        ///GEN	1	5	narrator-GEN		
        ///GEN	1	6	God		God (the LORD)
        ///GEN	1	8	narrator-GEN		
        ///GEN	1	9	God		God (the LORD)
        ///GEN	1	10	narrator-GEN		
        ///GEN	1	11	God		God (the LORD)
        ///GEN	1	14	God		God (the LORD)
        ///GEN	1	20	God		God (the LORD)
        ///GEN	1	22	God		God (the LORD)
        ///GEN	1	24	God		God (the LORD)
        ///GEN	1	26	God		God (the LORD)
        ///GEN	1	28	God	blessing	God (the LORD)
        ///GEN	1	29	God		God (the LORD)
        ///GEN	1	30	God		God (the LORD)
        ///GEN	2	16	G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterVerseData {
            get {
                return ResourceManager.GetString("CharacterVerseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;QuoteSystems&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, double&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, US/Canada&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;“&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;”&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Guillemets&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;French&lt;/MajorLanguage&gt;
        ///		&lt;StartQuoteMarker&gt;«&lt;/StartQuoteMarker&gt;
        ///		&lt;EndQuoteMarker&gt;»&lt;/EndQuoteMarker&gt;
        ///	&lt;/QuoteSystem&gt;
        ///	&lt;QuoteSystem&gt;
        ///		&lt;Name&gt;Quotation marks, single&lt;/Name&gt;
        ///		&lt;MajorLanguage&gt;English, UK&lt;/MajorLanguage&gt;
        ///		&lt;Star [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QuoteSystemData {
            get {
                return ResourceManager.GetString("QuoteSystemData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Marako Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Marako&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mar&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok ma Jon Labatija otit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleMRK {
            get {
                return ResourceManager.GetString("SampleMRK", resourceCulture);
            }
        }
    }
}
