//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoScript {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CharacterVerseData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CharacterVerseData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoScript.CharacterVerseData", typeof(CharacterVerseData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1CH	10	4	Saul	0414	
        ///1CH	11	1	Israel, all	0199	
        ///1CH	11	17	David	0093	
        ///1CH	11	19	David	0093	
        ///1CH	11	5	Jebusites	0243	
        ///1CH	11	6	David (had said)	0093	
        ///1CH	12	17	David	0093	
        ///1CH	12	18	Amasai, chief of thirty (Spirit came upon)	0029	
        ///1CH	12	19	Philistines, rulers of	0385	
        ///1CH	13	12	David, king	0093	
        ///1CH	13	2	David, king	0093	
        ///1CH	14	10	David, king	0093	
        ///1CH	14	10	God (the LORD)	2000	
        ///1CH	14	11	David, king	0093	
        ///1CH	14	14	God (the LORD)	2000	
        ///1CH	15	12	David, king	0093	
        ///1CH	15	2	David, king	0093	        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CharacterVerse {
            get {
                return ResourceManager.GetString("CharacterVerse", resourceCulture);
            }
        }
    }
}
