//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyssenTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyssenTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;JUD&quot; singlevoice=&quot;false&quot; pageheader=&quot;YӘHUDA&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot; matchesReferenceText=&quot;true&quot;&gt;
        ///    &lt;ReferenceBlocks style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot;&gt;
        ///      &lt;text&gt;JUDE&lt;/text&gt;
        ///    &lt;/ReferenceBlocks&gt;
        ///    &lt;text&gt;YӘHUDANIN MӘKTUBU&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;JUD&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot; matchesReferenceT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AzeriJUDRefText {
            get {
                return ResourceManager.GetString("AzeriJUDRefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;1JN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;1 JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Mukwoŋo Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;1 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;1 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MUKWOŊO ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok me kwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test1JN {
            get {
                return ResourceManager.GetString("Test1JN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;2JN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;2 JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Me Aryo Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;2 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;2 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA ME ARYO ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test2JN {
            get {
                return ResourceManager.GetString("Test2JN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;3JN&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;3 JON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Me Adek Ma Jon Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;3 Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;3 JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA ME ADEK ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Test3JN {
            get {
                return ResourceManager.GetString("Test3JN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;ACT&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;TIC PA LUKWENA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Tic Pa Lukwena&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Tic Pa Lukwena&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Tic&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;TIC PA LUKWENA&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lubaŋa ociko pi bino pa Cwiny Maleŋ&lt;/para&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestACT {
            get {
                return ResourceManager.GetString("TestACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment	Reference Comment
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John	
        ///250 Israelite leaders	250	Male	Adult			
        ///a Jew	1	Male	Adult			
        ///Aaron	1	Male	Adult			EXO 32:2 &lt;-(6 more)-&gt; NUM 12:12
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah	
        ///Abigail	1	Female	Adult			1SA 25:19 &lt;-(8 more)-&gt; 1SA 25:41
        ///Abijah, king of Judah	1	Male	Adult			2CH 13:4 &lt;-(7 more)-&gt; 2CH 13:12
        ///Abimelech, king of Gerar	1	Male	Adult			GEN 20:4 &lt;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterDetail {
            get {
                return ResourceManager.GetString("TestCharacterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment	Reference Comment
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John	
        ///250 Israelite leaders	250	Male	Adult			
        ///a Jew	1	Male	Adult			
        ///Aaron	1	Male	Adult			EXO 32:2 &lt;-(6 more)-&gt; NUM 12:12
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah	
        ///Abigail	1	Female	Adult			1SA 25:19 &lt;-(8 more)-&gt; 1SA 25:41
        ///Abijah, king of Judah	1	Male	Adult			2CH 13:4 &lt;-(7 more)-&gt; 2CH 13:12
        ///Abimelech, king of Gerar	1	Male	Adult			GEN 20:4 &lt;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterDetailOct2015 {
            get {
                return ResourceManager.GetString("TestCharacterDetailOct2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestCharacterGroups {
            get {
                object obj = ResourceManager.GetObject("TestCharacterGroups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	3	Generated	Thu, 04 Dec 2014 16:01:02 GMT
        ///GEN	1	3	God		God (the LORD)
        ///GEN	1	5	narrator-GEN		
        ///GEN	1	6	God		God (the LORD)
        ///GEN	1	8	narrator-GEN		
        ///GEN	1	9	God		God (the LORD)
        ///GEN	1	10	narrator-GEN		
        ///GEN	1	11	God		God (the LORD)
        ///GEN	1	14	God		God (the LORD)
        ///GEN	1	15	God		God (the LORD)
        ///GEN	1	20	God		God (the LORD)
        ///GEN	1	22	God		God (the LORD)
        ///GEN	1	24	God		God (the LORD)
        ///GEN	1	26	God		God (the LORD)
        ///GEN	1	28	God	blessing	God (the LORD)
        ///GEN	1	29	God		God (the LORD)
        ///GEN	1	30	G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterVerse {
            get {
                return ResourceManager.GetString("TestCharacterVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	79
        ///#	C	V	Character ID	Delivery	Alias	Quote Type	Default Character	Parallel Passage
        ///# This is a TEST version of this file. It corresponds to version 79 of the actual production file (in use as of October 2015).
        ///# It can be used together with TestCharacterDetailOct2015 for testing code that requires the character verse data and the
        ///# character detail data to be in synch.
        ///GEN	1	3	God		God (the LORD)	Normal		
        ///GEN	1	5	narrator-GEN			Quotation		
        ///#Languages which do not allow indirect s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterVerseOct2015 {
            get {
                return ResourceManager.GetString("TestCharacterVerseOct2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;EPH&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JO EPECO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Paulo Ocoyo Bot Jo Epeco&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jo Epeco&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Ep&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA PAULO OCOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO EPECO&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt;
        ///  &lt;para s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestEPH {
            get {
                return ResourceManager.GetString("TestEPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;GAL&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JO GALATIA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Paulo Ocoyo Bot Jo Galatia&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jo Galatia&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Gal&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA PAULO OCOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO GALATIA&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Mot&lt;/para&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestGAL {
            get {
                return ResourceManager.GetString("TestGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;HEB&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JO IBRU&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Gicoyo Bot Jo Ibru&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Jo Ibru&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Ibru&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA GICOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JO IBRU&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lubaŋa oloko kwedwa i Wode&lt;/para&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestHEB {
            get {
                return ResourceManager.GetString("TestHEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;JOS&quot; style=&quot;id&quot;&gt;- Kuna, San Blas - Bible -Panama 2014 (DBL -2014)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Josué&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Josué-Garda&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Josué&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Jos&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JOSUÉ-GARDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JOSUÉ&lt;/para&gt;
        ///  &lt;para style=&quot;imt2&quot;&gt;GEBE-SOGLENAID&lt;/para&gt;
        ///  &lt;para style=&quot;imt&quot;&gt;Garda-nug&lt;/para&gt;
        ///  &lt;para style=&quot;ip&quot;&gt;
        ///    &lt;char style=&quot;it&quot;&gt;Josué-Garda.&lt;/char&gt; Josu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJOS {
            get {
                return ResourceManager.GetString("TestJOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;JUD&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;JUDA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Juda Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Juda&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Juda&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;JUDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; styl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestJUD {
            get {
                return ResourceManager.GetString("TestJUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;LUK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;LUKA&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Luka Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Luka&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Luka&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;LUKA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok bot Teopilo&lt;/para&gt;
        ///  &lt;para [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestLUK {
            get {
                return ResourceManager.GetString("TestLUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Marako Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Marako&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mar&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok ma Jon Labatija otit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMRK {
            get {
                return ResourceManager.GetString("TestMRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;PHM&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;PILEMON&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Waraga Ma Paulo Ocoyo Bot Pilemon Mot&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Pilemon&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Pile&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;WARAGA MA PAULO OCOYO bot&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;PILEMON&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;Mot&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;par [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestPHM {
            get {
                return ResourceManager.GetString("TestPHM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;JUD&quot; singlevoice=&quot;false&quot; pageheader=&quot;JUDE&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot;&gt;
        ///    &lt;text&gt;JUDE&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;JUD&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot;&gt;
        ///    &lt;text&gt;1&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;p&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; initialStartVerse=&quot;1&quot; characterId=&quot;narrator-JUD&quot;&gt;
        ///    &lt;verse num=&quot;1&quot; /&gt;
        ///    &lt;text&gt;Jude, a servant of Jesus Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestReferenceTextJUD {
            get {
                return ResourceManager.GetString("TestReferenceTextJUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RelatedCharacterSets&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;Barzillai&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;Barzillai (old)&lt;/CharacterId&gt;
        ///	&lt;/RelatedCharacters&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;David&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;David (old)&lt;/CharacterId&gt;
        ///	&lt;/RelatedCharacters&gt;
        ///	&lt;RelatedCharacters RelationshipType=&quot;SameCharacterWithMultipleAges&quot;&gt;
        ///		&lt;CharacterId&gt;Elisha&lt;/CharacterId&gt;
        ///		&lt;CharacterId&gt;Elisha (old)&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRelatedCharacters {
            get {
                return ResourceManager.GetString("TestRelatedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;REV&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;NIYABO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Niyabo Bot Jon&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Niyabo&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Yabo&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;NIYABO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;BOT JON&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;p&quot;&gt;
        ///    &lt;verse number=&quot;1&quot; style=&quot;v&quot; /&gt;Man aye gin ma Lubaŋa onyuto [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestREV {
            get {
                return ResourceManager.GetString("TestREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;RUT&quot; style=&quot;id&quot;&gt;- Kuna, San Blas - Bible -Panama 2014 (DBL -2014)&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;Rut&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Rut-Garda&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Rut&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Rt&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;RUT-GARDA&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;RUT&lt;/para&gt;
        ///  &lt;para style=&quot;imt2&quot;&gt;GEBE-SOGLENAID&lt;/para&gt;
        ///  &lt;para style=&quot;imt&quot;&gt;Garda-nug&lt;/para&gt;
        ///  &lt;para style=&quot;ip&quot;&gt;
        ///    &lt;char style=&quot;it&quot;&gt;Rut-Garda.&lt;/char&gt; We-gardagine, bun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestRUT {
            get {
                return ResourceManager.GetString("TestRUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;Test&quot;
        ///# Version=1.9
        ///#
        ///# List of books, chapters, verses
        ///# One line per book.
        ///# One entry for each chapter.
        ///# Verse number is the maximum verse number for that chapter.
        ///# See the lines containing =&apos;s below for verse mappings.
        ///#
        ///#--------------------------------------------------
        ///# Old Testament
        ///GEN 1:31 2:25 3:24 4:26 5:32 6:22 7:24 8:22 9:29 10:32 11:32 12:20 13:18 14:24 15:21 16:16 17:27 18:33 19:38 20:18 21:34 22:24 23:20 24:67 25:34 26:35 27:46 28:22 29:35 30:43 31:54 32:33 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestVersification {
            get {
                return ResourceManager.GetString("TestVersification", resourceCulture);
            }
        }
    }
}
