//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyssenTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyssenTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] azeri {
            get {
                object obj = ResourceManager.GetObject("azeri", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] english {
            get {
                object obj = ResourceManager.GetObject("english", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] french {
            get {
                object obj = ResourceManager.GetObject("french", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] spanish {
            get {
                object obj = ResourceManager.GetObject("spanish", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment	Reference Comment
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John	
        ///250 Israelite leaders	250	Male	Adult			
        ///a Jew	1	Male	Adult			
        ///Aaron	1	Male	Adult			EXO 32:2 &lt;-(6 more)-&gt; NUM 12:12
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah	
        ///Abigail	1	Female	Adult			1SA 25:19 &lt;-(8 more)-&gt; 1SA 25:41
        ///Abijah, king of Judah	1	Male	Adult			2CH 13:4 &lt;-(7 more)-&gt; 2CH 13:12
        ///Abimelech, king of Gerar	1	Male	Adult			GEN 20:4 &lt;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterDetail {
            get {
                return ResourceManager.GetString("TestCharacterDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Character ID	Max Speakers	Gender	Age	Status	Comment	Reference Comment
        ///2 other disciples	2	Male	Adult		Not Peter (Simon), Thomas, Nathaniel, James, or John	
        ///250 Israelite leaders	250	Male	Adult			
        ///a Jew	1	Male	Adult			
        ///Aaron	1	Male	Adult			EXO 32:2 &lt;-(6 more)-&gt; NUM 12:12
        ///Abednego	1	Male	Adult		original Hebrew name: Azariah	
        ///Abigail	1	Female	Adult			1SA 25:19 &lt;-(8 more)-&gt; 1SA 25:41
        ///Abijah, king of Judah	1	Male	Adult			2CH 13:4 &lt;-(7 more)-&gt; 2CH 13:12
        ///Abimelech, king of Gerar	1	Male	Adult			GEN 20:4 &lt;- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterDetailOct2015 {
            get {
                return ResourceManager.GetString("TestCharacterDetailOct2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestCharacterGroups {
            get {
                object obj = ResourceManager.GetObject("TestCharacterGroups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	3	Generated	Thu, 04 Dec 2014 16:01:02 GMT
        ///GEN	1	3	God		God (the LORD)
        ///GEN	1	5	narrator-GEN		
        ///GEN	1	6	God		God (the LORD)
        ///GEN	1	8	narrator-GEN		
        ///GEN	1	9	God		God (the LORD)
        ///GEN	1	10	narrator-GEN		
        ///GEN	1	11	God		God (the LORD)
        ///GEN	1	14	God		God (the LORD)
        ///GEN	1	15	God		God (the LORD)
        ///GEN	1	20	God		God (the LORD)
        ///GEN	1	22	God		God (the LORD)
        ///GEN	1	24	God		God (the LORD)
        ///GEN	1	26	God		God (the LORD)
        ///GEN	1	28	God	blessing	God (the LORD)
        ///GEN	1	29	God		God (the LORD)
        ///GEN	1	30	G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterVerse {
            get {
                return ResourceManager.GetString("TestCharacterVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	79
        ///#	C	V	Character ID	Delivery	Alias	Quote Type	Default Character	Parallel Passage
        ///# This is a TEST version of this file. It corresponds to version 79 of the actual production file (in use as of October 2015).
        ///# It can be used together with TestCharacterDetailOct2015 for testing code that requires the character verse data and the
        ///# character detail data to be in synch.
        ///# This is a regex that can be used in VS to find places where the delivery changes for a character: (MAT\t[0-9]+\t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterVerseOct2015 {
            get {
                return ResourceManager.GetString("TestCharacterVerseOct2015", resourceCulture);
            }
        }
    }
}
