//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoScriptTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoScriptTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control File Version	3	Generated	Thu, 04 Dec 2014 16:01:02 GMT
        ///GEN	1	3	God		God (the LORD)
        ///GEN	1	5	narrator-GEN		
        ///GEN	1	6	God		God (the LORD)
        ///GEN	1	8	narrator-GEN		
        ///GEN	1	9	God		God (the LORD)
        ///GEN	1	10	narrator-GEN		
        ///GEN	1	11	God		God (the LORD)
        ///GEN	1	14	God		God (the LORD)
        ///GEN	1	20	God		God (the LORD)
        ///GEN	1	22	God		God (the LORD)
        ///GEN	1	24	God		God (the LORD)
        ///GEN	1	26	God		God (the LORD)
        ///GEN	1	28	God	blessing	God (the LORD)
        ///GEN	1	29	God		God (the LORD)
        ///GEN	1	30	God		God (the LORD)
        ///GEN	1	31	L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacterVerse {
            get {
                return ResourceManager.GetString("TestCharacterVerse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;usx version=&quot;2.0&quot;&gt;
        ///  &lt;book code=&quot;MRK&quot; style=&quot;id&quot;&gt;Acholi Bible 1985 Digitised by Africa Typesetting Network for DBL April 2013&lt;/book&gt;
        ///  &lt;para style=&quot;h&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;toc1&quot;&gt;Jiri Ma Marako Ocoyo&lt;/para&gt;
        ///  &lt;para style=&quot;toc2&quot;&gt;Marako&lt;/para&gt;
        ///  &lt;para style=&quot;toc3&quot;&gt;Mar&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;JIRI ma&lt;/para&gt;
        ///  &lt;para style=&quot;mt1&quot;&gt;MARAKO&lt;/para&gt;
        ///  &lt;para style=&quot;mt2&quot;&gt;ocoyo&lt;/para&gt;
        ///  &lt;chapter number=&quot;1&quot; style=&quot;c&quot; /&gt;
        ///  &lt;para style=&quot;s1&quot;&gt;Lok ma Jon Labatija otit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestMRK {
            get {
                return ResourceManager.GetString("TestMRK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;English&quot;
        ///# Version=1.9
        ///#
        ///# modifications by Reinier de Blois 13/March/2012
        ///# modified mappings Psalms by adding verse #0 to the mappings
        ///# many of the subscripts that are part of verses 1,2 in the original text end up as verse #0 in English translations
        ///
        ///# modifications by Studge 26/June/2009
        ///# book definitions are for all books printed in any English of Spanish Bible
        ///# this includes books for Protestant, Catholic and Protestant-Catholic-EasternOrthodox Interconfessional editions        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestVersification {
            get {
                return ResourceManager.GetString("TestVersification", resourceCulture);
            }
        }
    }
}
