//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlyssenSharedTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlyssenSharedTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata id=&quot;5453af4c7644271c&quot; type=&quot;text&quot; typeVersion=&quot;1.4&quot; revision=&quot;0&quot; usxparserversion=&quot;33&quot; origdblpath=&quot;C:\unknown&quot; controlfileversion=&quot;91&quot; modifieddate=&quot;2016-03-08T13:42:38.5231556-07:00&quot; firstchapterannouncement=&quot;true&quot; singlechapterannouncement=&quot;true&quot;&gt;
        ///  &lt;language&gt;
        ///    &lt;iso&gt;azb&lt;/iso&gt;
        ///    &lt;name&gt;Azeri&lt;/name&gt;
        ///    &lt;ldml&gt;azb&lt;/ldml&gt;
        ///    &lt;rod /&gt;
        ///    &lt;script /&gt;
        ///    &lt;numerals /&gt;
        ///    &lt;fontFamily&gt;Charis SIL&lt;/fontFamily&gt;
        ///    &lt;fontSizeInPoints&gt;14&lt;/fontSizeInPoi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string azeri_metadata {
            get {
                return ResourceManager.GetString("azeri_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;JUD&quot; singlevoice=&quot;false&quot; pageheader=&quot;YӘHUDA&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot; matchesReferenceText=&quot;true&quot;&gt;
        ///    &lt;ReferenceBlocks style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot;&gt;
        ///      &lt;text&gt;JUDE&lt;/text&gt;
        ///    &lt;/ReferenceBlocks&gt;
        ///    &lt;text&gt;YӘHUDANIN MӘKTUBU&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;JUD&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot; matchesReferenceT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AzeriJUDRefText {
            get {
                return ResourceManager.GetString("AzeriJUDRefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;REV&quot; singlevoice=&quot;false&quot; pageheader=&quot;VӘHY&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-REV&quot; matchesReferenceText=&quot;true&quot;&gt;
        ///    &lt;ReferenceBlocks style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-REV&quot;&gt;
        ///      &lt;text&gt;REVELATION&lt;/text&gt;
        ///    &lt;/ReferenceBlocks&gt;
        ///    &lt;text&gt;YӘHYAYA NAZİL OLAN&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;REV&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-REV&quot; matchesRefer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AzeriREVRefText {
            get {
                return ResourceManager.GetString("AzeriREVRefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata id=&quot;5453af4c7644271c&quot; type=&quot;text&quot; typeVersion=&quot;1.4&quot; revision=&quot;0&quot; usxparserversion=&quot;33&quot; origdblpath=&quot;X:\1 SCRIPT ASSEMBLER\Amgad\Director Guide into Glyssen\English\Glyssen script English DG\9 Apostrophies and r removed\export_text_dbl-5453af4c7644271c_pt-ENGDG_20160308-122600\bundle_text_dbl-5453af4c7644271c_pt-ENGDG_20160308-122600_release.zip&quot; controlfileversion=&quot;91&quot; audiostocknumber=&quot;ENGENG9Ap&quot; modifieddate=&quot;2016-03-08T13:42:38.5231556-07:00&quot; firstchap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english_metadata {
            get {
                return ResourceManager.GetString("english_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Versification  &quot;English&quot;
        ///# Version=1.9
        ///#
        ///# modifications by Reinier de Blois 13/March/2012
        ///# modified mappings Psalms by adding verse #0 to the mappings
        ///# many of the subscripts that are part of verses 1,2 in the original text end up as verse #0 in English translations
        ///
        ///# modifications by Studge 26/June/2009
        ///# book definitions are for all books printed in any English of Spanish Bible
        ///# this includes books for Protestant, Catholic and Protestant-Catholic-EasternOrthodox Interconfessional editions        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EnglishVersification {
            get {
                return ResourceManager.GetString("EnglishVersification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata id=&quot;5453af4c7644271c&quot; type=&quot;text&quot; typeVersion=&quot;1.4&quot; revision=&quot;0&quot; usxparserversion=&quot;33&quot; origdblpath=&quot;C:\unknown&quot; controlfileversion=&quot;91&quot; modifieddate=&quot;2016-03-08T13:42:38.5231556-07:00&quot; firstchapterannouncement=&quot;true&quot; singlechapterannouncement=&quot;true&quot;&gt;
        ///  &lt;language&gt;
        ///    &lt;iso&gt;fra&lt;/iso&gt;
        ///    &lt;name&gt;French&lt;/name&gt;
        ///    &lt;ldml&gt;fra&lt;/ldml&gt;
        ///    &lt;rod /&gt;
        ///    &lt;script /&gt;
        ///    &lt;numerals /&gt;
        ///    &lt;fontFamily&gt;Charis SIL&lt;/fontFamily&gt;
        ///    &lt;fontSizeInPoints&gt;14&lt;/fontSizeInPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string french_metadata {
            get {
                return ResourceManager.GetString("french_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;MAT&quot; singlevoice=&quot;false&quot; pageheader=&quot;MATTHIEU CHAPITRE&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MAT&quot; matchesReferenceText=&quot;true&quot;&gt;
        ///    &lt;ReferenceBlocks style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MAT&quot;&gt;
        ///      &lt;text&gt;MATTHEW&lt;/text&gt;
        ///    &lt;/ReferenceBlocks&gt;
        ///    &lt;text&gt;MATTHIEU&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;MAT&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MAT&quot; matchesRefer [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FrenchMATRefText {
            get {
                return ResourceManager.GetString("FrenchMATRefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;MRK&quot; singlevoice=&quot;false&quot; pageheader=&quot;MARC CHAPITRE&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MRK&quot; matchesReferenceText=&quot;true&quot;&gt;
        ///    &lt;ReferenceBlocks style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MRK&quot;&gt;
        ///      &lt;text&gt;MARK&lt;/text&gt;
        ///    &lt;/ReferenceBlocks&gt;
        ///    &lt;text&gt;MARC&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;MRK&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MRK&quot; matchesReferenceText=&quot;t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FrenchMRKRefText {
            get {
                return ResourceManager.GetString("FrenchMRKRefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;DBLMetadata id=&quot;5453af4c7644271c&quot; type=&quot;text&quot; typeVersion=&quot;1.4&quot; revision=&quot;0&quot; usxparserversion=&quot;33&quot; origdblpath=&quot;C:\unknown&quot; controlfileversion=&quot;91&quot; modifieddate=&quot;2016-03-08T13:42:38.5231556-07:00&quot; firstchapterannouncement=&quot;true&quot; singlechapterannouncement=&quot;true&quot;&gt;
        ///  &lt;language&gt;
        ///    &lt;iso&gt;spa&lt;/iso&gt;
        ///    &lt;name&gt;Spanish&lt;/name&gt;
        ///    &lt;ldml&gt;es&lt;/ldml&gt;
        ///    &lt;rod /&gt;
        ///    &lt;script /&gt;
        ///    &lt;numerals /&gt;
        ///    &lt;fontFamily&gt;Charis SIL&lt;/fontFamily&gt;
        ///    &lt;fontSizeInPoints&gt;14&lt;/fontSizeInPo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string spanish_metadata {
            get {
                return ResourceManager.GetString("spanish_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;MAT&quot; singlevoice=&quot;false&quot; pageheader=&quot;SAN MATEO&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MAT&quot; matchesReferenceText=&quot;true&quot;&gt;
        ///    &lt;ReferenceBlocks style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MAT&quot;&gt;
        ///      &lt;text&gt;MATTHEW&lt;/text&gt;
        ///    &lt;/ReferenceBlocks&gt;
        ///    &lt;text&gt;SAN ... MATEO&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;MAT&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-MAT&quot; matchesReferenc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SpanishMATRefText {
            get {
                return ResourceManager.GetString("SpanishMATRefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;book id=&quot;JUD&quot; singlevoice=&quot;false&quot; pageheader=&quot;JUDE&quot;&gt;
        ///  &lt;block style=&quot;mt&quot; chapter=&quot;0&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot;&gt;
        ///    &lt;text&gt;JUDE&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;c&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; book=&quot;JUD&quot; initialStartVerse=&quot;0&quot; characterId=&quot;BC-JUD&quot;&gt;
        ///    &lt;text&gt;1&lt;/text&gt;
        ///  &lt;/block&gt;
        ///  &lt;block style=&quot;p&quot; paragraphStart=&quot;true&quot; chapter=&quot;1&quot; initialStartVerse=&quot;1&quot; characterId=&quot;narrator-JUD&quot;&gt;
        ///    &lt;verse num=&quot;1&quot; /&gt;
        ///    &lt;text&gt;Jude, a servant of Jesus Ch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestReferenceTextJUD {
            get {
                return ResourceManager.GetString("TestReferenceTextJUD", resourceCulture);
            }
        }
    }
}
